name: CinematicBuilder
version: 1.0
main: io.papermc.cinematicbuilder.CinematicBuilder
description: plugin to create cinematics
author: Alejomc26
api-version: '1.20'
default-permission: true

commands:
  cinematicbuilder:
    description: Command to manage cinematics
    aliases:
      - cb